# Site ayarları
title: Herbalife
description: Herbalife ve Herbalife ürünleri hakkında detaylı bilgi almak için doğru adresdesiniz.
baseurl: "/docs"
url: "https://lydacar.github.io/herbalife.com/" 
theme: jekyll-theme-primer
sass:
  style: compressed
